export class StoreResponse {
  storeInfoId: string = '';
  storeInfoSts: string = '';
  storeInfoChk: string = '';
  storeInfoCreated: string = '';
  storeInfoUpdated: string = '';
  storeInfoData: string = '';
  storeInfoName: string = '';
  storeInfoType: string = '';
  storeInfoAddress1: string = '';
  storeInfoCity: string = '';
  storeInfoState: string = '';
  storeInfoArea: string = '';
  storeInfoZip: string = '';
  storeInfoCountry: string = '';
  storeInfoCounty: string = '';
  storeInfoLocale: string = '';
  storeInfoCurrencyId: string = '';
  storeInfoLatitude: string = '';
  storeInfoLongitude: string = '';
  storeInfoPhone: string = '';
  storeInfoDescription: string = '';
  storeInfoManager: string = '';
  storeInfoEmail: string = '';
  storeInfoTax: string = '';
  storeInfoLocType: string = '';
}
